### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by mwallnoefer** [SunBuild/drupalcms-azure#3]
The Drupal installation tells me that an update to release 8.3.2 should be performed, since among other improvements and corrections it also fixes security bugs.
BTW: How often does the software get updated? Do there exist some maintenance plans?

**Comment by workbrien** [comment]
@mwallnoefer  @SunBuild  I'm using Azure to build a Drupal site is there currently a way to update latest release?

**Comment by mwallnoefer** [comment]
I did not follow this anymore since this was just a personal trial. So for production scenarios I would not suggest to use this images if they are so outdated. Better stick with your personally maintained stack.

**Comment by workbrien** [comment]
Thanks @mwallnoefer for the quick response. I'll look into alternatives.
